//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RUTAS_UISRAELEntities : DbContext
    {
        public DB_RUTAS_UISRAELEntities()
            : base("name=DB_RUTAS_UISRAELEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNO> ALUMNO { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<Rutas> Rutas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_transporte> Tipo_transporte { get; set; }
        public virtual DbSet<Trasporte> Trasporte { get; set; }
    }
}
