//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int Id_reserva { get; set; }
        public Nullable<int> Id_ruta { get; set; }
        public Nullable<int> Id_Alumno { get; set; }
        public Nullable<System.DateTime> Fecha_Reserva { get; set; }
        public string Estado_Reserva { get; set; }
        public string Codigo_Reserva { get; set; }
    
        public virtual ALUMNO ALUMNO { get; set; }
        public virtual Rutas Rutas { get; set; }
    }
}
