//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trasporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trasporte()
        {
            this.Rutas = new HashSet<Rutas>();
        }
    
        public string Placa_trasporte { get; set; }
        public Nullable<int> Id_tipo_trasporte { get; set; }
        public string capacidad { get; set; }
        public Nullable<bool> Estado_trasporte { get; set; }
        public int Id_trasporte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rutas> Rutas { get; set; }
        public virtual Tipo_transporte Tipo_transporte { get; set; }
    }
}
